[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable environment variable support
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = true

# RPC URLs - configurable via environment variables
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

# Etherscan API keys
[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
